services:
  - name: learning-tailwind
    type: web
    env: node
    buildCommand: npm run build
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
    buildTimeout: 900
